In [1]:
import pandas as pd

1. Write a Pandas program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

In [2]:
ds = pd.Series([2, 4, 6, 8, 10])
print(ds)

0     2
1     4
2     6
3     8
4    10
dtype: int64

2. Write a Pandas program to convert a Panda module Series to Python list and it's type.

In [5]:
series = pd.Series([2, 4, 6, 8, 10])
lista = series.tolist()
print(ds)
print(type(ds))
print(lista)
print(type(lista))

0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
[2, 4, 6, 8, 10]
<class 'list'>

3. Write a Pandas program to add, subtract, multiple and divide two Pandas Series.

In [10]:
serie_a = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
serie_b = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
print('Add two Series:')
print(serie_a + serie_b)
print('Subtract two Series:')
print(serie_a - serie_b)
print('Multiply two Series:')
print(serie_a * serie_b)
print('Divide two Series:')
print(serie_a / serie_b)

Add two Series:
0    11
1    11
2    11
3    11
4    11
5    11
6    11
7    11
8    11
9    11
dtype: int64
Subtract two Series:
0   -9
1   -7
2   -5
3   -3
4   -1
5    1
6    3
7    5
8    7
9    9
dtype: int64
Multiply two Series:
0    10
1    18
2    24
3    28
4    30
5    30
6    28
7    24
8    18
9    10
dtype: int64
Divide two Series:
0     0.100000
1     0.222222
2     0.375000
3     0.571429
4     0.833333
5     1.200000
6     1.750000
7     2.666667
8     4.500000
9    10.000000
dtype: float64

4. Write a Pandas program to compare the elements of the two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [11]:
d1 = pd.Series([2, 4, 6, 8, 10])
d2 = pd.Series([1, 3, 5, 7, 9])